version: '3.8'

services:
  test_py38_dj3219:
    image: python:3.8-slim-bullseye
    environment:
      - PYTHONWARNINGS=always
    volumes:
      - .:/django-heartbeat
    command: sh -c "
      cd django-heartbeat;
      pip install --upgrade pip;
      pip install Django==3.2.19 pytest pytest-html;
      pip install -e .;
      pytest tests -vv --html=./test-results_py38_dj3219.html --self-contained-html
      "

  test_py38_dj40:
    image: python:3.8-slim-bullseye
    environment:
      - PYTHONWARNINGS=always
    volumes:
      - .:/django-heartbeat
    command: sh -c "
      cd django-heartbeat;
      pip install --upgrade pip;
      pip install Django==4.0 pytest pytest-html;
      pip install -e .;
      pytest tests -vv --html=./test-results_py38_dj40.html --self-contained-html
      "

  test_py310_dj3219:
    image: python:3.10-slim-bullseye
    environment:
      - PYTHONWARNINGS=always
    volumes:
      - .:/django-heartbeat
    command: sh -c "
      cd django-heartbeat;
      pip install --upgrade pip;
      pip install Django==3.2.19 pytest pytest-html;
      pip install -e .;
      pytest tests -vv --html=./test-results_py310_dj3219.html --self-contained-html
      "

  test_py310_dj40:
    image: python:3.10-slim-bullseye
    environment:
      - PYTHONWARNINGS=always
    volumes:
      - .:/django-heartbeat
    command: sh -c "
      cd django-heartbeat;
      pip install --upgrade pip;
      pip install Django==4.0 pytest pytest-html;
      pip install -e .;
      pytest tests -vv --html=./test-results_py40_dj40.html --self-contained-html
      "
