version: '3.8'

services:
  test_py38_dj427:
    image: python:3.8-slim-bullseye
    environment:
      - PYTHONWARNINGS=always
    volumes:
      - .:/django-heartbeat
    command: sh -c "
      cd django-heartbeat;
      pip install --upgrade pip;
      pip install Django==4.2.7 pytest pytest-html;
      pip install -e .;
      pytest tests -vv --html=./test-results_py38_dj427.html --self-contained-html
      "

  test_py310_dj427:
    image: python:3.10-slim-bullseye
    environment:
      - PYTHONWARNINGS=always
    volumes:
      - .:/django-heartbeat
    command: sh -c "
      cd django-heartbeat;
      pip install --upgrade pip;
      pip install Django==4.2.7 pytest pytest-html;
      pip install -e .;
      pytest tests -vv --html=./test-results_py310_dj427.html --self-contained-html
      "
