name: Publish

on:
  workflow_call:
    secrets:
      TWINE_USERNAME:
        required: true
      TWINE_PASSWORD:
        required: true
    inputs:
      TWINE_REPOSITORY:
        required: false
        type: string
        default: 'testpypi'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      TWINE_REPOSITORY: ${{ inputs.TWINE_REPOSITORY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Upload package
        run: |
          pip install --upgrade pip
          pip install --upgrade twine
          pip install --upgrade build
          env | grep TWINE_REPOSITORY
          if [ $TWINE_REPOSITORY == 'testpypi' ]; 
          then 
            # rename package because we've lost access to the official test-pypi project
            # renaming the package only for testpipy so that it can be published there
            # will remove if I am successfull in contacting Andrei Pradan
            sed -i 's/name = "django-heartbeat"/name = "django-heartbeat-testpipy"/g' pyproject.toml; 
          fi;
          cat pyproject.toml
#          python3 -m build
#          python3 -m twine upload dist/*
