name: Run Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          docker-compose down
          docker-compose run --rm test_py38_dj427
          docker-compose down
          docker-compose run --rm test_py310_dj427
          docker-compose down
      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path:
            test-results_*
        if: ${{ always() }}
